FROM debian:latest
RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y \
        autotools-dev \
        automake \
        build-essential \
        check \
        debhelper \
        devscripts \
        doxygen \
        git \
        git-buildpackage \
        libedit-dev \
        libssl-dev \
        libtool \
        man \
        pkg-config \
        valgrind \
        vim

